### ISSUE TITLE
Investigate possible emscripten bugs

### ISSUE THREAD

**Issue by satoshinm** [satoshinm/NetCraft#50]
Develop small test cases and possible fixes for emscripten instead of only working-around in this repo.

This is all on emscripten 1.37.0, current latest emsdk.

With workarounds:

- [x] `glfwGetInputMode(g->window, GLFW_CURSOR) == GLFW_CURSOR_DISABLED` after `glfwSetInputMode(g->window, GLFW_CURSOR, GLFW_CURSOR_DISABLED);` - expect no-op/fail since can't request pointer lock (=GLFW_CURSOR_DISABLED) without user action? and/or glfwGetInputMode(GLFW_CURSOR) should get actual pointer lock status, like `emscripten_get_pointerlock_status()`.  https://github.com/satoshinm/NetCraft/issues/39 Mouse look triggers even when pointer lock inactive on first load  **added in https://github.com/satoshinm/emglfwbugs/blob/gh-pages/test_glfw_cursor_disabled/test_glfw_cursor_disabled.c**

- [x] `pointerlockchange` should re-enable cursor, since it is ~equivalent to pointer lock: `glfwSetInputMode(g->window, GLFW_CURSOR, GLFW_CURSOR_NORMAL);` https://github.com/satoshinm/NetCraft/issues/44 Mouse look triggers even when pointer lock inactivated **added in https://github.com/satoshinm/emglfwbugs/blob/gh-pages/test_glfw_cursor_disabled/test_glfw_cursor_disabled.c**

- [x] `glfwSetCharCallback` should not be called when Cmd is down, since that's not typing a charcater: https://github.com/satoshinm/NetCraft/issues/46 Cmd-Backquote types the Backquote keystroke to write on signs, instead of doing nothing **added in https://github.com/satoshinm/emglfwbugs/blob/gh-pages/test_glfw_char_callback/test_glfw_char_callback.c**

Without yet, may require emscripten fixes:

- [x] `onblur` should reset key state for `glfwGetKey()` etc.: https://github.com/satoshinm/NetCraft/issues/40 Keys stick - missing keyup event when losing focus? **added in https://github.com/satoshinm/emglfwbugs/blob/gh-pages/test_glfw_get_key_stuck/test_glfw_get_key_stuck.c**, partial workaround (ignore on blur, but sticks when refocus) and also changed https://github.com/satoshinm/NetCraft/issues/51
- [x] `emscripten_enter_soft_fullscreen()` shouldn't remove `<body>` that's crazy: https://github.com/satoshinm/NetCraft/issues/49 Soft fullscreen removes `<body>` element so document.body.style causes null deref **added in https://github.com/satoshinm/emglfwbugs/blob/gh-pages/test_fullscreen_fullwindow_toggle/test_fullscreen_fullwindow_toggle.c**, https://github.com/satoshinm/NetCraft/pull/52

**Comment by satoshinm** [comment]
Isolated all the issues, developed tests/workarounds at https://github.com/satoshinm/emglfwbugs and submitted to https://github.com/kripken/emscripten/ issue tracker
